services:
  db:
    image: mysql:8.0
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1;"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 25s
      
  redis:
    image: redis:alpine
    container_name: redisContainer
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s      
      timeout: 5s         
      retries: 3          
      start_period: 5s

  app:
    image: ghcr.io/wladp27/go-solution:latest
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - ConnectionStrings__RedisConnection=${ConnectionStrings__RedisConnection}
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy



volumes:
  mysql_data: