<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components" Version="10.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Forms" Version="10.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.0" />
		<PackageReference Include="BootstrapBlazor" Version="10.9.0" />
	

		<PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
		<PackageReference Include="FluentResults" Version="4.0.0" />
		<PackageReference Include="MediatR" Version="14.0.0" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Features\Auth\Components\" />
		<Folder Include="Features\City\Components\" />
		<Folder Include="Features\Location\Components\" />
		<Folder Include="Features\TypeEvent\Pages\" />
	</ItemGroup>

</Project>